# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync
# is not defined and the default is used.

cu_cp:
  amf:
    addr: 127.0.1.100
    port: 38412
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "NETWORK_MCCNETWORK_MNC"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: serial=USRP_ID,num_recv_frames=64,num_send_frames=64
  # sync: external
  clock: external
  srate: 23.04 # 30.72
  otw_format: sc12
  tx_gain: 60
  rx_gain: 50

cell_cfg:
  dl_arfcn: 368500 #627340
  band: 3 #78
  channel_bandwidth_MHz: 20 #15
  common_scs: 15 #30
  plmn: "NETWORK_MCCNETWORK_MNC"
  tac: 7
  pci: 1

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
